In [8]:
import torch
import numpy as np
import QuSelfAttn as Q

## self-attention practice

In [9]:
cir = Q.QEqualizedConv0(2)

In [10]:
print(f"n_qubits:{cir.n_qubits}")

n_qubits:2


In [11]:
U = cir.qconv0()
print(U.shape)
print(U)

torch.Size([4, 4])
tensor([[ 0.3391+0.3352j, -0.2237-0.3045j, -0.4811-0.3944j,  0.3275+0.3684j],
        [ 0.0470+0.3749j, -0.0156+0.4766j, -0.1065-0.4813j, -0.0375-0.6209j],
        [ 0.0375-0.6209j, -0.1065+0.4813j, -0.0156-0.4766j, -0.0470+0.3749j],
        [ 0.3275-0.3684j,  0.4811-0.3944j,  0.2237-0.3045j,  0.3391-0.3352j]],
       grad_fn=<MmBackward>)


In [13]:
U2 = cir.qconv_q()
print(U2.shape)
print(U2)

torch.Size([4, 4])
tensor([[ 0.2550+0.6875j, -0.1141-0.5697j,  0.0133-0.2764j, -0.0447+0.2146j],
        [-0.1779+0.5531j, -0.3312+0.6542j,  0.1436-0.1657j,  0.2118-0.1781j],
        [-0.2118-0.1781j,  0.1436+0.1657j, -0.3312-0.6542j,  0.1779+0.5531j],
        [-0.0447-0.2146j, -0.0133-0.2764j,  0.1141-0.5697j,  0.2550-0.6875j]],
       grad_fn=<MmBackward>)


In [14]:
cir.forward(U)

tensor([[ 0.3391+0.3352j, -0.2237-0.3045j, -0.4811-0.3944j,  0.3275+0.3684j],
        [ 0.0470+0.3749j, -0.0156+0.4766j, -0.1065-0.4813j, -0.0375-0.6209j],
        [ 0.0375-0.6209j, -0.1065+0.4813j, -0.0156-0.4766j, -0.0470+0.3749j],
        [ 0.3275-0.3684j,  0.4811-0.3944j,  0.2237-0.3045j,  0.3391-0.3352j]],
       grad_fn=<MmBackward>)

In [15]:
cir.forward(U2)

tensor([[-0.0868-0.0948j,  0.0562+0.0850j, -0.5850-0.5055j,  0.3950+0.4683j],
        [-0.0076-0.1016j,  0.0106-0.1282j, -0.1168-0.6014j, -0.0265-0.7727j],
        [ 0.0265-0.7727j, -0.1168+0.6014j,  0.0106+0.1282j,  0.0076-0.1016j],
        [ 0.3950-0.4683j,  0.5850-0.5055j, -0.0562+0.0850j, -0.0868+0.0948j]],
       grad_fn=<MmBackward>)

## prepare initial data (classical)
### Input 1: [1， 0， 1， 0]; Input 2: [0， 2， 0， 2]; Input 3: [1， 1， 1， 1];

In [5]:
input01 = torch.Tensor([1, 0, 1, 0])
input02 = torch.Tensor([0, 2, 0, 2])
input03 = torch.Tensor([1, 1, 1, 1])

In [6]:
qinput01 = Q.vector2rho(input01)

cir.forward(qinput01)

tensor([[ 0.0935+2.7940e-09j, -0.0914-7.7199e-04j,  0.0006-1.9765e-01j,
         -0.0022+1.9318e-01j],
        [-0.0914+7.7199e-04j,  0.0893-1.8626e-09j,  0.0011+1.9319e-01j,
          0.0006-1.8884e-01j],
        [ 0.0006+1.9765e-01j,  0.0011-1.9319e-01j,  0.4179+0.0000e+00j,
         -0.4085-3.4515e-03j],
        [-0.0022-1.9318e-01j,  0.0006+1.8884e-01j, -0.4085+3.4515e-03j,
          0.3993-1.8626e-09j]], grad_fn=<MmBackward>)

In [ ]:
one_query = 

In [ ]:
one_key = 

In [ ]:
one_value = 

In [7]:
qinput02 = Q.vector2rho(input02)

cir.forward(qinput02)

tensor([[ 0.0893+3.7253e-09j,  0.0914+7.7201e-04j,  0.0006-1.8884e-01j,
          0.0022-1.9318e-01j],
        [ 0.0914-7.7201e-04j,  0.0935-2.7940e-09j, -0.0011-1.9319e-01j,
          0.0006-1.9765e-01j],
        [ 0.0006+1.8884e-01j, -0.0011+1.9319e-01j,  0.3993-7.4506e-09j,
          0.4085+3.4515e-03j],
        [ 0.0022+1.9318e-01j,  0.0006+1.9765e-01j,  0.4085-3.4515e-03j,
          0.4179-1.1176e-08j]], grad_fn=<MmBackward>)

In [8]:
qinput03 = Q.vector2rho(input03)

cir.forward(qinput03)

tensor([[ 1.8152e-01-3.9581e-09j,  2.1800e-03-1.4971e-02j,
          1.1281e-03-3.8382e-01j, -3.1643e-02-4.7025e-03j],
        [ 2.1800e-03+1.4971e-02j,  1.2610e-03+0.0000e+00j,
          3.1670e-02-4.5164e-03j,  7.8361e-06-2.6662e-03j],
        [ 1.1281e-03+3.8382e-01j,  3.1670e-02+4.5164e-03j,
          8.1158e-01+9.3132e-10j,  9.7465e-03-6.6936e-02j],
        [-3.1643e-02+4.7025e-03j,  7.8364e-06+2.6662e-03j,
          9.7465e-03+6.6936e-02j,  5.6377e-03+6.9849e-10j]],
       grad_fn=<MmBackward>)

量子线路的构建方法需要变化