In [1]:
import torch
import numpy as np
import QuSelfAttn as Q

In [2]:
qc = Q.Circuit(3)

In [3]:
# qc.rx(2,0.5)

In [4]:
# qc.ry(1,1)

In [5]:
# qc.rz(1,1)

In [6]:
qc.Hcz(1,1)

In [7]:
# qc.z_gate(1)

In [8]:
# qc.rxx(1,1)

In [9]:
# qc.cnot(1,2)

In [10]:
qc.show_gates()


 gate in sequence is : [{'gate': 'I', 'theta': None, 'which_qubit': 1}, {'gate': 'Z', 'theta': None, 'which_qubit': 1}]


In [11]:
qc.gate_list

[{'gate': 'I', 'theta': None, 'which_qubit': 1},
 {'gate': 'Z', 'theta': None, 'which_qubit': 1}]

In [12]:
qc.read_gate()


 index: 0
 gate_list:{'gate': 'I', 'theta': None, 'which_qubit': 1}
 gate_matrix: tensor([[1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j]])
 circuit_matrix: tensor([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])
 U: tensor([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+

In [13]:
qc.U 

tensor([[ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j]])

## Test RXX-Gate math representation

In [19]:
from math import pi
phi_0 = 0
phi_1 = pi/2
phi_2 = pi

In [25]:
print(Q.rxx(phi_0))
print(Q.rxx(phi_1))
print(Q.rxx(phi_2))

tensor([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])
tensor([[0.7071+0.0000j, 0.0000+0.0000j, 0.0000+0.0000j, 0.0000-0.7071j],
        [0.0000+0.0000j, 0.7071+0.0000j, 0.0000-0.7071j, 0.0000+0.0000j],
        [0.0000+0.0000j, 0.0000-0.7071j, 0.7071+0.0000j, 0.0000+0.0000j],
        [0.0000-0.7071j, 0.0000+0.0000j, 0.0000+0.0000j, 0.7071+0.0000j]])
tensor([[6.1232e-17+0.j, 0.0000e+00+0.j, 0.0000e+00+0.j, 0.0000e+00-1.j],
        [0.0000e+00+0.j, 6.1232e-17+0.j, 0.0000e+00-1.j, 0.0000e+00+0.j],
        [0.0000e+00+0.j, 0.0000e+00-1.j, 6.1232e-17+0.j, 0.0000e+00+0.j],
        [0.0000e+00-1.j, 0.0000e+00+0.j, 0.0000e+00+0.j, 6.1232e-17+0.j]])


In [26]:
print(Q.ryy(phi_0))
print(Q.ryy(phi_1))
print(Q.ryy(phi_2))

tensor([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])
tensor([[0.7071+0.0000j, 0.0000+0.0000j, 0.0000+0.0000j, 0.0000+0.7071j],
        [0.0000+0.0000j, 0.7071+0.0000j, 0.0000-0.7071j, 0.0000+0.0000j],
        [0.0000+0.0000j, 0.0000-0.7071j, 0.7071+0.0000j, 0.0000+0.0000j],
        [0.0000+0.7071j, 0.0000+0.0000j, 0.0000+0.0000j, 0.7071+0.0000j]])
tensor([[6.1232e-17+0.j, 0.0000e+00+0.j, 0.0000e+00+0.j, 0.0000e+00+1.j],
        [0.0000e+00+0.j, 6.1232e-17+0.j, 0.0000e+00-1.j, 0.0000e+00+0.j],
        [0.0000e+00+0.j, 0.0000e+00-1.j, 6.1232e-17+0.j, 0.0000e+00+0.j],
        [0.0000e+00+1.j, 0.0000e+00+0.j, 0.0000e+00+0.j, 6.1232e-17+0.j]])


In [31]:
print(Q.rzz(0))
print(Q.rzz(2*pi))
print(Q.rzz(pi/2))

tensor([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])
tensor([[-1.+8.7423e-08j,  0.+0.0000e+00j,  0.+0.0000e+00j,  0.+0.0000e+00j],
        [ 0.+0.0000e+00j, -1.-8.7423e-08j,  0.+0.0000e+00j,  0.+0.0000e+00j],
        [ 0.+0.0000e+00j,  0.+0.0000e+00j, -1.-8.7423e-08j,  0.+0.0000e+00j],
        [ 0.+0.0000e+00j,  0.+0.0000e+00j,  0.+0.0000e+00j, -1.+8.7423e-08j]])
tensor([[0.7071-0.7071j, 0.0000+0.0000j, 0.0000+0.0000j, 0.0000+0.0000j],
        [0.0000+0.0000j, 0.7071+0.7071j, 0.0000+0.0000j, 0.0000+0.0000j],
        [0.0000+0.0000j, 0.0000+0.0000j, 0.7071+0.7071j, 0.0000+0.0000j],
        [0.0000+0.0000j, 0.0000+0.0000j, 0.0000+0.0000j, 0.7071-0.7071j]])
